version: "2.3"
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
       - ./redis:/data
  node:
    build: .
    restart: always
    ports:
      - 4567:4567
    depends_on:
      - redis
    volumes:
      - ./video:/video
      - ./config.json:/root/config.json
    environment:
      - REDIS_URL=redis://redis:6379
      - VIDEO_DIR=/video
#      - SLACK_HOOKURL=
